In [54]:
import pandas as pd

# just the links
seattlewiki="https://en.wikipedia.org/wiki/Seattle"
newyorkwiki="https://en.wikipedia.org/wiki/New_York_City"
bostonwiki="https://en.wikipedia.org/wiki/Boston"

# data frames as lists:

seattletab=pd.read_html(seattlewiki, # link
                        header=0, # where is the header?
                        flavor='bs4', # helper to translate html
                        attrs={'class': 'wikitable'})
newyorktab=pd.read_html(newyorkwiki, # link
                        header=0, # where is the header?
                        flavor='bs4', # helper to translate html
                        attrs={'class': 'wikitable'})
bostontab=pd.read_html(bostonwiki, # link
                        header=0, # where is the header?
                        flavor='bs4', # helper to translate html
                        attrs={'class': 'wikitable'})

Tables needed:

In [55]:
dataSea=seattletab[1].copy()
dataSea

,Racial composition,2020[113],2010[114],1990[38],1970[38],1940[38]
0,White (non-Hispanic),59.5%,66.3%,73.7%,85.3%[c],NaN
1,Asian (non-Hispanic),16.9%,13.7%,11.8%,4.2%,2.8%
2,Hispanic or Latino,8.2%,6.6%,3.6%,2.0%[c],NaN
3,Black or African American (non-Hispanic),6.8%,7.7%,10.1%,7.1%,1.0%
4,Other (non-Hispanic),0.6%,0.2%,NaN,NaN,NaN
5,Two or more races (non-Hispanic),7.3%,4.4%,NaN,NaN,NaN

In [56]:
dataBos=bostontab[2].copy()
dataBos

,Race/ethnicity,2020[146],2010[147],1990[142],1970[142],1940[142]
0,Non-Hispanic Whites,44.7%,47.0%,59.0%,79.5%[f],96.6%
1,Black,22.0%,24.4%,23.8%,16.3%,3.1%
2,Hispanic or Latino (of any race),19.5%,17.5%,10.8%,2.8%[f],0.1%
3,Asian,9.7%,8.9%,5.3%,1.3%,0.2%
4,Two or more races,3.2%,3.9%,–,–,–
5,Native American,0.2%,0.4%,0.3%,0.2%,–

In [57]:
dataNY=newyorktab[3].copy()
dataNY

,Historical demographics,2020[250],2010[251],1990[252],1970[252],1940[252]
0,White (non-Hispanic),30.9%,33.3%,43.4%,64.0%,92.1%
1,Hispanic or Latino,28.3%,28.6%,23.7%,15.2%,1.6%
2,Black or African American (non-Hispanic),20.2%,22.8%,28.8%,21.1%,6.1%
3,Asian and Pacific Islander (non-Hispanic),15.6%,12.6%,7.0%,1.2%,0.2%
4,Native American (non-Hispanic),0.2%,0.2%,0.4%,0.1%,NaN
5,Two or more races (non-Hispanic),3.4%,1.8%,NaN,NaN,NaN

Here:
We want to concatenate the three data frames, but the names are different due to the "[...]", and alos the first columns is different.

In [58]:
dataBos.columns

Index(['Race/ethnicity', '2020[146]', '2010[147]', '1990[142]', '1970[142]',
       '1940[142]'],
      dtype='object')

In [59]:
# BYE anything that looks like \[.+\], where .+ means one or more character:
dataBos.columns.str.replace('\[.+\]|\s|\/.+','', regex=True)

Index(['Race', '2020', '2010', '1990', '1970', '1940'], dtype='object')

In [60]:
#Then:
dataSea.columns=dataSea.columns.str.replace('\[.+\]|\s|\/.+','', regex=True)
dataBos.columns=dataBos.columns.str.replace('\[.+\]|\s|\/.+','', regex=True)
dataNY.columns=dataNY.columns.str.replace('\[.+\]|\s|\/.+','', regex=True)

In [61]:
# now:
dataSea.columns

Index(['Racialcomposition', '2020', '2010', '1990', '1970', '1940'], dtype='object')

In [62]:
dataBos.columns

Index(['Race', '2020', '2010', '1990', '1970', '1940'], dtype='object')

In [63]:
dataNY.columns

Index(['Historicaldemographics', '2020', '2010', '1990', '1970', '1940'], dtype='object')

In [64]:
#Are they all the same?
set(dataNY.columns)&set(dataBos.columns)&set(dataSea.columns)

{'1940', '1970', '1990', '2010', '2020'}

In [65]:
(set(dataSea.columns)^set(dataNY.columns))

{'Historicaldemographics', 'Racialcomposition'}

In [66]:
dataSea.columns=dataNY.columns=dataBos.columns

Now

In [67]:
set(dataSea.columns)&set(dataNY.columns)&set(dataBos.columns)

{'1940', '1970', '1990', '2010', '2020', 'Race'}

In [68]:
dataSea['City']='Seattle'
dataNY['City']='NY'
dataBos['City']='Boston'

Let's concatenate:

In [69]:
SeaNYBos=pd.concat([dataSea,dataNY,dataBos])
SeaNYBos

,Race,2020,2010,1990,1970,1940,City
0,White (non-Hispanic),59.5%,66.3%,73.7%,85.3%[c],NaN,Seattle
1,Asian (non-Hispanic),16.9%,13.7%,11.8%,4.2%,2.8%,Seattle
2,Hispanic or Latino,8.2%,6.6%,3.6%,2.0%[c],NaN,Seattle
3,Black or African American (non-Hispanic),6.8%,7.7%,10.1%,7.1%,1.0%,Seattle
4,Other (non-Hispanic),0.6%,0.2%,NaN,NaN,NaN,Seattle
5,Two or more races (non-Hispanic),7.3%,4.4%,NaN,NaN,NaN,Seattle
0,White (non-Hispanic),30.9%,33.3%,43.4%,64.0%,92.1%,NY
1,Hispanic or Latino,28.3%,28.6%,23.7%,15.2%,1.6%,NY
2,Black or African American (non-Hispanic),20.2%,22.8%,28.8%,21.1%,6.1%,NY
3,Asian and Pacific Islander (non-Hispanic),15.6%,12.6%,7.0%,1.2%,0.2%,NY
4,Native American (non-Hispanic),0.2%,0.2%,0.4%,0.1%,NaN,NY
5,Two or more races (non-Hispanic),3.4%,1.8%,NaN,NaN,NaN,NY
0,Non-Hispanic Whites,44.7%,47.0%,59.0%,79.5%[f],96.6%,Boston
1,Black,22.0%,24.4%,23.8%,16.3%,3.1%,Boston
2,Hispanic or Latino (of any race),19.5%,17.5%,10.8%,2.8%[f],0.1%,Boston
3,Asian,9.7%,8.9%,5.3%,1.3%,0.2%,Boston
4,Two or more races,3.2%,3.9%,–,–,–,Boston
5,Native American,0.2%,0.4%,0.3%,0.2%,–,Boston

In [70]:
#standardizing the race column

changes={"White (non-Hispanic)":"White",
"Non-Hispanic Whites":"White",
"Asian (non-Hispanic)":"Asian",
"Asian and Pacific Islander (non-Hispanic)":"Asian",
"Hispanic or Latino (of any race)":"Hispanic or Latino",
"Black or African American (non-Hispanic)":"Black",
"Native American (non-Hispanic)":"Native American",
"Other (non-Hispanic)":"Other",
"Native American (non-Hispanic)":"Other",
"Native American":"Other",
"Two or more races (non-Hispanic)":"Two or more races"}

In [71]:
SeaNYBos.Race.replace(to_replace=changes,inplace=True)
SeaNYBos

                 Race   2020   2010   1990      1970   1940     City
0               White  59.5%  66.3%  73.7%  85.3%[c]    NaN  Seattle
1               Asian  16.9%  13.7%  11.8%      4.2%   2.8%  Seattle
2  Hispanic or Latino   8.2%   6.6%   3.6%   2.0%[c]    NaN  Seattle
3               Black   6.8%   7.7%  10.1%      7.1%   1.0%  Seattle
4               Other   0.6%   0.2%    NaN       NaN    NaN  Seattle
5   Two or more races   7.3%   4.4%    NaN       NaN    NaN  Seattle
0               White  30.9%  33.3%  43.4%     64.0%  92.1%       NY
1  Hispanic or Latino  28.3%  28.6%  23.7%     15.2%   1.6%       NY
2               Black  20.2%  22.8%  28.8%     21.1%   6.1%       NY
3               Asian  15.6%  12.6%   7.0%      1.2%   0.2%       NY
4               Other   0.2%   0.2%   0.4%      0.1%    NaN       NY
5   Two or more races   3.4%   1.8%    NaN       NaN    NaN       NY
0               White  44.7%  47.0%  59.0%  79.5%[f]  96.6%   Boston
1               Black  22.0%  24.4%  23.8%     16.3%   3.1%   Boston
2  Hispanic or Latino  19.5%  17.5%  10.8%   2.8%[f]   0.1%   Boston
3               Asian   9.7%   8.9%   5.3%      1.3%   0.2%   Boston
4   Two or more races   3.2%   3.9%      –         –      –   Boston
5               Other   0.2%   0.4%   0.3%      0.2%      –   Boston

In [72]:
#setting city and race as indices
SeaNYBos.set_index(['City', 'Race'],inplace=True)
SeaNYBos

                             2020   2010   1990      1970   1940
City    Race
Seattle White               59.5%  66.3%  73.7%  85.3%[c]    NaN
        Asian               16.9%  13.7%  11.8%      4.2%   2.8%
        Hispanic or Latino   8.2%   6.6%   3.6%   2.0%[c]    NaN
        Black                6.8%   7.7%  10.1%      7.1%   1.0%
        Other                0.6%   0.2%    NaN       NaN    NaN
        Two or more races    7.3%   4.4%    NaN       NaN    NaN
NY      White               30.9%  33.3%  43.4%     64.0%  92.1%
        Hispanic or Latino  28.3%  28.6%  23.7%     15.2%   1.6%
        Black               20.2%  22.8%  28.8%     21.1%   6.1%
        Asian               15.6%  12.6%   7.0%      1.2%   0.2%
        Other                0.2%   0.2%   0.4%      0.1%    NaN
        Two or more races    3.4%   1.8%    NaN       NaN    NaN
Boston  White               44.7%  47.0%  59.0%  79.5%[f]  96.6%
        Black               22.0%  24.4%  23.8%     16.3%   3.1%
        Hispanic or Latino  19.5%  17.5%  10.8%   2.8%[f]   0.1%
        Asian                9.7%   8.9%   5.3%      1.3%   0.2%
        Two or more races    3.2%   3.9%      –         –      –
        Other                0.2%   0.4%   0.3%      0.2%      –

In [73]:
bracketchanges={"85.3%[c]":"85.3%",
               "2.0%[c]":"2.0%",
               "79.5%[f]":"79.5%",
               "2.8%[f]":"2.8%",}

SeaNYBos.replace(to_replace=bracketchanges,inplace=True)
SeaNYBos

                             2020   2010   1990   1970   1940
City    Race
Seattle White               59.5%  66.3%  73.7%  85.3%    NaN
        Asian               16.9%  13.7%  11.8%   4.2%   2.8%
        Hispanic or Latino   8.2%   6.6%   3.6%   2.0%    NaN
        Black                6.8%   7.7%  10.1%   7.1%   1.0%
        Other                0.6%   0.2%    NaN    NaN    NaN
        Two or more races    7.3%   4.4%    NaN    NaN    NaN
NY      White               30.9%  33.3%  43.4%  64.0%  92.1%
        Hispanic or Latino  28.3%  28.6%  23.7%  15.2%   1.6%
        Black               20.2%  22.8%  28.8%  21.1%   6.1%
        Asian               15.6%  12.6%   7.0%   1.2%   0.2%
        Other                0.2%   0.2%   0.4%   0.1%    NaN
        Two or more races    3.4%   1.8%    NaN    NaN    NaN
Boston  White               44.7%  47.0%  59.0%  79.5%  96.6%
        Black               22.0%  24.4%  23.8%  16.3%   3.1%
        Hispanic or Latino  19.5%  17.5%  10.8%   2.8%   0.1%
        Asian                9.7%   8.9%   5.3%   1.3%   0.2%
        Two or more races    3.2%   3.9%      –      –      –
        Other                0.2%   0.4%   0.3%   0.2%      –

In [75]:
SeaNYBos.fillna("–", inplace = True)
SeaNYBos

                             2020   2010   1990   1970   1940
City    Race
Seattle White               59.5%  66.3%  73.7%  85.3%      –
        Asian               16.9%  13.7%  11.8%   4.2%   2.8%
        Hispanic or Latino   8.2%   6.6%   3.6%   2.0%      –
        Black                6.8%   7.7%  10.1%   7.1%   1.0%
        Other                0.6%   0.2%      –      –      –
        Two or more races    7.3%   4.4%      –      –      –
NY      White               30.9%  33.3%  43.4%  64.0%  92.1%
        Hispanic or Latino  28.3%  28.6%  23.7%  15.2%   1.6%
        Black               20.2%  22.8%  28.8%  21.1%   6.1%
        Asian               15.6%  12.6%   7.0%   1.2%   0.2%
        Other                0.2%   0.2%   0.4%   0.1%      –
        Two or more races    3.4%   1.8%      –      –      –
Boston  White               44.7%  47.0%  59.0%  79.5%  96.6%
        Black               22.0%  24.4%  23.8%  16.3%   3.1%
        Hispanic or Latino  19.5%  17.5%  10.8%   2.8%   0.1%
        Asian                9.7%   8.9%   5.3%   1.3%   0.2%
        Two or more races    3.2%   3.9%      –      –      –
        Other                0.2%   0.4%   0.3%   0.2%      –